import type { Metadata } from 'next'
import { Inter, Roboto } from 'next/font/google'
import './styles/globals.css'
import Nav from './components/navigation/nav'

const roboto = Roboto({
  weight: '400',
  subsets: ['latin'],
})

export const metadata: Metadata = {
  title: {
    template: `Backlog Gamers | %s`,
    default: 'Backlog Gamers'
  }, 
  description: 'Generated by create next app',
  robots: {
    index: true,
    follow: true,
    nocache: true,
    googleBot: {
      index: true,
      follow: true,
      noimageindex: true
    },
  },
  openGraph: {
    title: 'Backlog Gamers',
    description: '',
    url: 'https://backloggamers.com',
    siteName: 'Backlog Gamers',
    // images: [
    //   {
    //     url: 'https://nextjs.org/og.png',
    //     width: 800,
    //     height: 600,
    //   },
    //   {
    //     url: 'https://nextjs.org/og-alt.png',
    //     width: 1800,
    //     height: 1600,
    //     alt: 'My custom alt',
    //   },
    // ],
    locale: 'en_US',
    type: 'website',
  },
  twitter: {
    card: 'summary_large_image',
    title: 'Backlog Gamers',
    description: '',
    siteId: '',
    creator: '@BacklogXGamers',
    creatorId: '',
    // images: ['https://nextjs.org/og.png'],
  }
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={roboto.className}>
        <header>
          <Nav/>
        </header>
        <main>
          {children}
        </main>
      </body>
    </html>
  )
}
